//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPopulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignmentDetail()
        {
            this.AssignmentGrades = new HashSet<AssignmentGrade>();
            this.SectionAssignments = new HashSet<SectionAssignment>();
        }
    
        public int AssignmentID { get; set; }
        public int AssignmentTypeID { get; set; }
        public double PointValue { get; set; }
        public string AssignmentTitle { get; set; }
    
        public virtual AssignmentType AssignmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentGrade> AssignmentGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionAssignment> SectionAssignments { get; set; }
    }
}
