//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPopulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentGrade
    {
        public int SubmissionNum { get; set; }
        public int StudentId { get; set; }
        public int SectionAssignmentId { get; set; }
        public Nullable<double> Grade { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string SubmissionFile { get; set; }
    
        public virtual SectionAssignment SectionAssignment { get; set; }
        public virtual Student Student { get; set; }
    }
}
