//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPopulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeWeight
    {
        public int SectionID { get; set; }
        public int AssignmentTypeID { get; set; }
        public double WeightPercent { get; set; }
    
        public virtual AssignmentType AssignmentType { get; set; }
        public virtual Section Section { get; set; }
    }
}
