//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPopulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterGradeScale
    {
        public int SectionID { get; set; }
        public string LetterGrade { get; set; }
        public Nullable<double> GradeHigh { get; set; }
        public Nullable<double> GradeLow { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
