//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPopulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionAssignment
    {
        public int SectionId { get; set; }
        public int AssignmentID { get; set; }
        public System.DateTime OpenDate { get; set; }
        public System.DateTime DueDate { get; set; }
    
        public virtual AssignmentDetail AssignmentDetail { get; set; }
        public virtual Section Section { get; set; }
    }
}
