//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPopulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SectionAssignment()
        {
            this.AssignmentGrades = new HashSet<AssignmentGrade>();
        }
    
        public int SectionAssignmentId { get; set; }
        public int SectionId { get; set; }
        public int AssignmentId { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual AssignmentDetail AssignmentDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentGrade> AssignmentGrades { get; set; }
        public virtual Section Section { get; set; }
    }
}
